package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
)

const envFileTemplate = `# Impress CMS Configuration
# Generated by Impress setup

PORT={{.Port}}
DB_DSN={{.DBDSN}}
JWT_SECRET={{.JWTSecret}}
JWT_REFRESH_SECRET={{.JWTRefreshSecret}}
ENV={{.Env}}
UPLOAD_DIR={{.UploadDir}}
BACKUP_DIR={{.BackupDir}}
# FRONTEND_DIR=./frontend/out
# BASE_URL=https://your-domain.com
# CORS_ALLOWED_ORIGINS=http://localhost:3000
`

// EnvFileParams holds values written into a .env file.
type EnvFileParams struct {
	Port             int
	DBDSN            string
	JWTSecret        string
	JWTRefreshSecret string
	Env              string
	UploadDir        string
	BackupDir        string
}

// DefaultEnvFilePath returns the path used for Impress environment configuration.
func DefaultEnvFilePath() string {
	if p := strings.TrimSpace(os.Getenv("IMPRESS_ENV_FILE")); p != "" {
		return p
	}
	return ".env"
}

// EnvFileConfigured reports whether a persisted .env file with JWT secrets exists.
func EnvFileConfigured() bool {
	path := DefaultEnvFilePath()
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	content := string(data)
	return strings.Contains(content, "JWT_SECRET=") && strings.Contains(content, "JWT_REFRESH_SECRET=")
}

// GenerateJWTSecrets returns cryptographically random JWT signing secrets.
func GenerateJWTSecrets() (secret string, refresh string, err error) {
	secret, err = randomSecret(32)
	if err != nil {
		return "", "", err
	}
	refresh, err = randomSecret(32)
	if err != nil {
		return "", "", err
	}
	return secret, refresh, nil
}

// WriteEnvFile writes configuration to the given directory's .env file.
func WriteEnvFile(outputDir string, params EnvFileParams) (string, error) {
	if params.Env == "" {
		params.Env = "development"
	}
	if params.UploadDir == "" {
		params.UploadDir = "./uploads"
	}
	if params.BackupDir == "" {
		params.BackupDir = "./backups"
	}
	if params.Port == 0 {
		params.Port = 8088
	}
	if params.JWTSecret == "" || params.JWTRefreshSecret == "" {
		secret, refresh, err := GenerateJWTSecrets()
		if err != nil {
			return "", err
		}
		if params.JWTSecret == "" {
			params.JWTSecret = secret
		}
		if params.JWTRefreshSecret == "" {
			params.JWTRefreshSecret = refresh
		}
	}

	if outputDir == "" {
		outputDir = "."
	}
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return "", fmt.Errorf("create output directory: %w", err)
	}

	envPath := DefaultEnvFilePath()
	if !filepath.IsAbs(envPath) {
		envPath = filepath.Join(outputDir, envPath)
	}

	tmpl, err := template.New("env").Parse(envFileTemplate)
	if err != nil {
		return "", fmt.Errorf("parse env template: %w", err)
	}

	f, err := os.OpenFile(envPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600)
	if err != nil {
		return "", fmt.Errorf("create env file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, params); err != nil {
		return "", fmt.Errorf("write env file: %w", err)
	}

	if err := os.MkdirAll(filepath.Join(outputDir, "data"), 0o755); err != nil {
		return "", fmt.Errorf("create data directory: %w", err)
	}
	uploadPath := params.UploadDir
	if !filepath.IsAbs(uploadPath) {
		uploadPath = filepath.Join(outputDir, strings.TrimPrefix(uploadPath, "./"))
	}
	if err := os.MkdirAll(uploadPath, 0o755); err != nil {
		return "", fmt.Errorf("create uploads directory: %w", err)
	}
	backupPath := params.BackupDir
	if !filepath.IsAbs(backupPath) {
		backupPath = filepath.Join(outputDir, strings.TrimPrefix(backupPath, "./"))
	}
	if err := os.MkdirAll(backupPath, 0o755); err != nil {
		return "", fmt.Errorf("create backups directory: %w", err)
	}

	return envPath, nil
}

func randomSecret(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

// ParsePort validates and returns a listen port.
func ParsePort(port int) (int, error) {
	if port <= 0 {
		return 8088, nil
	}
	if port > 65535 {
		return 0, fmt.Errorf("port must be between 1 and 65535")
	}
	return port, nil
}

// ParsePortString parses a port string with default fallback.
func ParsePortString(raw string) (int, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return 8088, nil
	}
	port, err := strconv.Atoi(raw)
	if err != nil {
		return 0, fmt.Errorf("port must be a valid integer")
	}
	return ParsePort(port)
}
