package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

const envTemplate = `# Impress CMS Configuration
# Generated by: impress init

PORT={{.Port}}
DB_DSN={{.DBDSN}}
JWT_SECRET={{.JWTSecret}}
JWT_REFRESH_SECRET={{.JWTRefreshSecret}}
ENV=development
UPLOAD_DIR=./uploads
# FRONTEND_DIR=./frontend/out
# BASE_URL=https://your-domain.com
# CORS_ALLOWED_ORIGINS=http://localhost:3000
`

type initConfig struct {
	Port             string
	DBDSN            string
	JWTSecret        string
	JWTRefreshSecret string
}

func initCmd() *cobra.Command {
	var nonInteractive bool
	var port, dbType, outputDir string

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize a new Impress CMS project",
		Long:  "Interactive project initialization: choose database, port, and generate .env configuration file.",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg := &initConfig{}
			reader := bufio.NewReader(os.Stdin)

			if nonInteractive {
				cfg.Port = port
				if dbType == "postgres" {
					cfg.DBDSN = "postgres://impress:impress@localhost:5432/impress?sslmode=disable"
				} else {
					cfg.DBDSN = "file:./data/blotting.db?cache=shared&mode=rwc"
				}
			} else {
				fmt.Print("Port [8088]: ")
				input, _ := reader.ReadString('\n')
				cfg.Port = strings.TrimSpace(input)
				if cfg.Port == "" {
					cfg.Port = "8088"
				}

				fmt.Print("Database (sqlite/postgres) [sqlite]: ")
				input, _ = reader.ReadString('\n')
				dbChoice := strings.TrimSpace(input)
				if dbChoice == "" || dbChoice == "sqlite" {
					cfg.DBDSN = "file:./data/blotting.db?cache=shared&mode=rwc"
				} else {
					fmt.Print("PostgreSQL DSN [postgres://impress:impress@localhost:5432/impress?sslmode=disable]: ")
					input, _ = reader.ReadString('\n')
					cfg.DBDSN = strings.TrimSpace(input)
					if cfg.DBDSN == "" {
						cfg.DBDSN = "postgres://impress:impress@localhost:5432/impress?sslmode=disable"
					}
				}
			}

			// Generate random-ish secrets (in production users should replace these)
			cfg.JWTSecret = "change-me-jwt-secret-" + fmt.Sprintf("%d", os.Getpid())
			cfg.JWTRefreshSecret = "change-me-jwt-refresh-" + fmt.Sprintf("%d", os.Getpid())

			// Write .env file
			outDir := outputDir
			if outDir == "" {
				outDir = "."
			}
			// Ensure output directory exists
			if err := os.MkdirAll(outDir, 0755); err != nil {
				return fmt.Errorf("failed to create output directory %s: %w", outDir, err)
			}

			envPath := filepath.Join(outDir, ".env")

			tmpl, err := template.New("env").Parse(envTemplate)
			if err != nil {
				return fmt.Errorf("failed to parse template: %w", err)
			}

			f, err := os.Create(envPath)
			if err != nil {
				return fmt.Errorf("failed to create %s: %w", envPath, err)
			}
			defer f.Close()

			if err := tmpl.Execute(f, cfg); err != nil {
				return fmt.Errorf("failed to write config: %w", err)
			}

			// Create data and uploads directories
			os.MkdirAll(filepath.Join(outDir, "data"), 0755)
			os.MkdirAll(filepath.Join(outDir, "uploads"), 0755)

			fmt.Printf("Configuration written to %s\n", envPath)
			fmt.Println("Directories created: data/, uploads/")
			fmt.Println("\nNext steps:")
			fmt.Println("  1. Review and update .env (especially JWT secrets)")
			fmt.Println("  2. Run: impress migrate up")
			fmt.Println("  3. Run: impress seed")
			fmt.Println("  4. Run: impress serve")
			return nil
		},
	}

	cmd.Flags().BoolVar(&nonInteractive, "non-interactive", false, "Skip interactive prompts")
	cmd.Flags().StringVar(&port, "port", "8088", "Server port (non-interactive mode)")
	cmd.Flags().StringVar(&dbType, "db", "sqlite", "Database type: sqlite or postgres (non-interactive mode)")
	cmd.Flags().StringVarP(&outputDir, "output", "o", ".", "Output directory for config files")

	return cmd
}
