#!/usr/bin/env bash
# Shared helpers for Quick-Box artifact deploy scripts.
set -euo pipefail

qb_log_info() { echo "[qb-artifact][INFO] $*"; }

qb_heartbeat_loop() {
  while sleep 60; do
    echo "[qb-artifact][heartbeat] $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >&2
  done
}

qb_run_with_heartbeat() {
  qb_heartbeat_loop &
  local hb_pid=$!
  trap 'kill "${hb_pid}" 2>/dev/null || true' RETURN
  "$@"
}
qb_log_warn() { echo "[qb-artifact][WARN] $*" >&2; }
qb_log_error() { echo "[qb-artifact][ERROR] $*" >&2; }

qb_repo_root() {
  cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd
}

qb_resolve_version() {
  if [[ -n "${QB_VERSION:-}" ]]; then
    echo "${QB_VERSION}"
    return 0
  fi
  local root="${1:-}"
  if [[ -n "${root}" ]] && [[ -d "${root}/.git" ]]; then
    git -C "${root}" describe --tags --always --dirty 2>/dev/null || echo "v0.0.0-unknown"
    return 0
  fi
  echo "v0.0.0-unknown"
}

qb_sha256_file() {
  local file="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "${file}" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "${file}" | awk '{print $1}'
  else
    qb_log_error "sha256sum or shasum required"
    return 1
  fi
}

qb_verify_checksum_file() {
  local artifact="$1"
  local checksum_file="$2"
  if [[ ! -f "${checksum_file}" ]]; then
    qb_log_warn "checksum file missing: ${checksum_file}"
    return 0
  fi
  if command -v sha256sum >/dev/null 2>&1; then
    (cd "$(dirname "${artifact}")" && sha256sum -c "$(basename "${checksum_file}")")
  elif command -v shasum >/dev/null 2>&1; then
    (cd "$(dirname "${artifact}")" && shasum -a 256 -c "$(basename "${checksum_file}")")
  fi
}

qb_component_enabled() {
  local name="$1"
  local list="${QB_BUILD_COMPONENTS:-backend,frontend}"
  [[ ",${list}," == *",${name},"* ]]
}

qb_artifact_incoming_dir() {
  if [[ -n "${QB_ARTIFACT_INCOMING:-}" ]]; then
    echo "${QB_ARTIFACT_INCOMING}"
  elif [[ -n "${QB_STAGING_PATH:-}" ]]; then
    echo "${QB_STAGING_PATH}"
  else
    qb_log_error "QB_ARTIFACT_INCOMING or QB_STAGING_PATH is required"
    return 1
  fi
}

qb_release_root() {
  echo "${QB_RELEASE_ROOT:-/opt/impress}"
}

qb_health_url() {
  echo "${QB_HEALTH_CHECK_URL:-${HEALTH_CHECK_URL:-http://127.0.0.1:8088/health}}"
}

qb_systemd_unit() {
  echo "${QB_SYSTEMD_UNIT:-impress}"
}

qb_runtime_type() {
  echo "${QB_RUNTIME_TYPE:-systemd}"
}

qb_atomic_symlink() {
  local target="$1"
  local link="$2"
  local tmp="${link}_tmp"
  ln -snf "${target}" "${tmp}"
  mv -Tf "${tmp}" "${link}"
}

qb_backup_current_symlink() {
  local base="$1"
  local current="${base}/current"
  local previous="${base}/previous"
  if [[ -L "${current}" ]]; then
  local current_target
    current_target="$(readlink "${current}")"
    ln -snf "${current_target}" "${previous}"
  fi
}

qb_write_env_file() {
  local env_file="$1"
  local release_root="$2"
  mkdir -p "$(dirname "${env_file}")"
  {
    echo "# Generated by qb-artifact-activate at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    [[ -n "${PORT:-}" ]] && echo "PORT=${PORT}"
    [[ -n "${ENV:-}" ]] && echo "ENV=${ENV}"
    [[ -n "${SEED_MODE:-}" ]] && echo "SEED_MODE=${SEED_MODE}"
    [[ -n "${SETUP_BOOTSTRAP:-}" ]] && echo "SETUP_BOOTSTRAP=${SETUP_BOOTSTRAP}"
    echo "FRONTEND_DIR=${FRONTEND_DIR:-${release_root}/frontend/current}"
    echo "UPLOAD_DIR=${UPLOAD_DIR:-${release_root}/uploads}"
    [[ -n "${DB_DSN:-}" ]] && echo "DB_DSN=${DB_DSN}"
    [[ -n "${JWT_SECRET:-}" ]] && echo "JWT_SECRET=${JWT_SECRET}"
    [[ -n "${JWT_REFRESH_SECRET:-}" ]] && echo "JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}"
  } >"${env_file}"
  chmod 600 "${env_file}" 2>/dev/null || true
}

qb_restart_runtime() {
  local release_root="$1"
  local unit
  unit="$(qb_systemd_unit)"
  local runtime
  runtime="$(qb_runtime_type)"

  if [[ "${runtime}" == "systemd" ]] && command -v systemctl >/dev/null 2>&1; then
    if ! systemctl is-enabled "${unit}" >/dev/null 2>&1; then
      qb_log_warn "systemd unit ${unit} not enabled; attempting start anyway"
    fi
    systemctl daemon-reload 2>/dev/null || true
    systemctl restart "${unit}"
    sleep 2
    if ! systemctl is-active --quiet "${unit}"; then
      qb_log_error "systemd unit ${unit} failed to start"
      systemctl status "${unit}" --no-pager || true
      return 1
    fi
    return 0
  fi

  qb_log_warn "systemd unavailable; using process mode on :${PORT:-8088}"
  local pid
  pid="$(ss -tlnp "sport = :${PORT:-8088}" 2>/dev/null | grep -oP 'pid=\K\d+' | head -1 || true)"
  if [[ -n "${pid}" ]]; then
    kill "${pid}" 2>/dev/null || true
    sleep 1
  fi
  local backend_dir="${release_root}/backend/current"
  local log_file="/tmp/impress-backend.log"
  # shellcheck disable=SC1091
  set -a
  source "${release_root}/backend/.env"
  set +a
  nohup "${backend_dir}/blotting-api-latest" >"${log_file}" 2>&1 &
  sleep 3
}

qb_health_check() {
  local url
  url="$(qb_health_url)"
  local retries="${QB_HEALTH_CHECK_RETRIES:-10}"
  local interval="${QB_HEALTH_CHECK_INTERVAL_SEC:-3}"
  local i=1
  while [[ "${i}" -le "${retries}" ]]; do
    if curl -sf --max-time 5 "${url}" >/dev/null; then
      qb_log_info "health check passed: ${url}"
      return 0
    fi
    qb_log_warn "health check attempt ${i}/${retries} failed: ${url}"
  sleep "${interval}"
    i=$((i + 1))
  done
  qb_log_error "health check failed after ${retries} attempts: ${url}"
  return 1
}
